### ISSUE TITLE
Use volume containers instead of host mounted volume

### ISSUE THREAD

**Issue by sils1297** [yesnault/docker-phabricator#19]
I'd recommend to use a volume container to split the data from the phabricator container.

I do this:

```bash
docker run --name="phabricator_data" \
-v /var/lib/mysql \
-v /var/repo \
-v /opt/phabricator/conf \
sils1297/centos /bin/echo phabricator data container

docker run --name="phabricator" -d --restart=always -p 80:80 -p 25:25 \
--volumes-from phabricator_data \
yesnault/docker-phabricator
```

This makes the whole thing independent from the hosts filesystem while keeping the data isolated. The phabricator_data container is just there to assure the volume doesnt get cleaned up if one docker rm's the phabricator container. Another advantage is that you dont have to fiddle with the permissions/selinux and so on on the host system which is usually ugly.

There will be no pull request for this since I use my own setup script together with other containers. Its just a suggestion of what I think might be better ;).

**Comment by yesnault** [comment]
see https://github.com/yesnault/docker-phabricator-alone
