### ISSUE TITLE
can't host repositories on phabricator

### ISSUE THREAD

**Issue by sils1297** [yesnault/docker-phabricator#20]
for http the /usr/bin/git-core directory has to go into phabricators path variable. After that there are some access problems. Would be nice to adress that.

**Comment by alberto56** [comment]
I am experiencing the same problem:

 * create a diffusion repo and make it accessible via ssh
 * upload my ssh key
 * try to push to that repository
 * system requests my password

**Comment by yesnault** [comment]
@sils1297  Could you make a PR ?

**Comment by sils1297** [comment]
I didn't manage to fix it by now. Sorry.

**Comment by alberto56** [comment]
For more info on installing repo hosting, please see https://secure.phabricator.com/book/phabricator/article/diffusion_hosting/

**Comment by yesnault** [comment]
fixed by https://github.com/yesnault/docker-phabricator/commit/6788d5375f18d4074c9ae13c1dcc7dafe55144fe
