### ISSUE TITLE
Can Not Connect to MySQL

### ISSUE THREAD

**Issue by rotatingJazz** [yesnault/docker-phabricator#23]
What are the proper user/pass values to make it connect? Or do we set this manually in mysql and phab's local config?

**Comment by rotatingJazz** [comment]
I ended-up doing this:
- Open a shell
- Edit supervisor config to start mysql with `--skip-grant-tables`
- Kill mysqld
- Change `root` passwd
- Update phab's config via `./bin/config`
- Kill mysqld again

**Comment by alberto56** [comment]
Here is the behaviour I got:

(1) everything working
(2) created root account on the web interface
(3) clicked on 9 unresolved install issues

One of them was "Please set up authentication method".

When I clicked on that, all subsequent pages, including the home page, give the following error:

    AphrontConnectionQueryException
    Attempt to connect to root@localhost failed with error #2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2).

**Comment by alberto56** [comment]
Confirming that this issue can be a symptom of not enough RAM.

**Comment by yesnault** [comment]
Yes, mysql is really "greedy" :-D I think this container needs a least 1 Gb RAM.

**Comment by sils1297** [comment]
Maybe add a troubleshoot section to readme mentioning this issue?
