### ISSUE TITLE
Apache php.ini default

### ISSUE THREAD

**Issue by rotatingJazz** [yesnault/docker-phabricator#24]
`upload_max_filesize` should be set in higher limit by default in `/etc/php5/apache2/php.ini` to resolve one to the "unresolved issues" during the initial `phabricator` configuration.

**Comment by yesnault** [comment]
Could you make a PR ?

**Comment by yesnault** [comment]
already fixed, see https://github.com/yesnault/docker-phabricator/blob/master/Dockerfile#L54
