### ISSUE TITLE
Explain in a comment why the build step contains --no-cache

### ISSUE THREAD

**Issue by alberto56** [yesnault/docker-phabricator#25]
It's not clear in https://github.com/yesnault/docker-phabricator/blob/master/build.sh why --no-cache is used. 

Perhaps the reasoning behind --no-cache can be added as a comment.

**Comment by yesnault** [comment]
It's a docker option to docker run cmd.
see. https://docs.docker.com/reference/builder/#run

It is here to not reused cache of previous build.
