### ISSUE TITLE
Cannot start container

### ISSUE THREAD

**Issue by caske33** [yesnault/docker-phabricator#28]
When I run `docker run --name databasePhabricator yesnault/docker-phabricator-mysql` and then `docker run -p 8081:80 --link databasePhabricator:database yesnault/docker-phabricator`, I get the next response on the second command

`Error response from daemon: Cannot start container 7fe5f4cb95b72e7511fcb2a03889f237ec960d20372d942672dedb9a4a2fc263: Cannot link to a non running container: /databasePhabricator AS /evil_mcclintock/database`

The first container stops running for a reason... Is there a way I can fix this?

**Comment by yesnault** [comment]
I uploaded a new version of phabricator image, seems all working weel. Feel free to reopen this issue if it's not working for you.
