### ISSUE TITLE
"You have 7 unresolved setup issues"

### ISSUE THREAD

**Issue by hourback** [yesnault/docker-phabricator#33]
What's the best way to handle the setup issues mentioned after installing?  Log into an intermediate container and make the changes?

**Comment by yesnault** [comment]
I think the best way is (I think) to docker exec -it into phabricator container. You need to configure  baseUri /config/issue/config.phabricator.base-uri/, authent provider (/config/issue/auth.noproviders/), this configuration can be different for each phabricator instance.
