### ISSUE TITLE
Mysql setup is overridden by volume

### ISSUE THREAD

**Issue by adarshaj** [yesnault/docker-phabricator#34]
If you pass a volume while starting database, then the mysql script executed in https://github.com/yesnault/docker-phabricator/blob/60cff4a6610a5f4506a34096afbbf4d3abfc362f/database/Dockerfile#L23 would have its effect nullified due to the fact that it would have modified the container's mysql data path - `/var/lib/mysql`

**Comment by yesnault** [comment]
Now, phabricator image needs mysql image.
docker run --name databasePhabricator yesnault/docker-phabricator-mysql
docker run -p 8081:80 --link databasePhabricator:database yesnault/docker-phabricator 

This issue is no longer relevant, feel free to reopen if necessary.
