### ISSUE TITLE
Phabricator Daemons Aren't Running

### ISSUE THREAD

**Issue by AusIV** [yesnault/docker-phabricator#39]
Phabricator has a number of daemons that are presumed to be running on the same host as the Apache service, but the docker container doesn't run the daemons. This means a number of features of Phabricator don't work. I've tried starting them with docker exec, and they start, but they start as root because the "sudo" command is unavailable on the image. The web service runs as www-data, so there are path permission conflicts if the daemons create a file that the web service will later need to edit.

**Comment by michaeljs1990** [comment]
https://github.com/michaeljs1990/Dockerfiles/tree/master/phabricator has daemons properly running if you want to take a look. I am not saying this is a production ready dockerfile in my repo however it is more functional than this version.

**Comment by yesnault** [comment]
fixed by https://github.com/yesnault/docker-phabricator/commit/6788d5375f18d4074c9ae13c1dcc7dafe55144fe
