### ISSUE TITLE
AphrontSchemaQueryException

### ISSUE THREAD

**Issue by hotmeatballsoup** [yesnault/docker-phabricator#41]
I have Docker running on a remote Ubuntu VM (say, `app01.example.com`).

I ran:

    docker run --name databasePhabricator yesnault/docker-phabricator-mysql

Then I ran:

    docker run -p 8081:80 --link databasePhabricator:database yesnault/docker-phabricator

Just to verify everything started correctly, I ran `docker logs sick_bartik` (the `docker-phabricator` image) and saw this error message:

    AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.7. Set the 'ServerName' directive globally to suppress this message

I then opened up a browser and went to `http://app01.example.com:8081` and the Phabricator UI showed up. Great success! The first thing Phabricator wants you to do is set up an Admin account. So I filled out the simple form (admin username, name, email, etc.), submitted the form, and got the following exception:

<img width="1240" alt="screen shot 2015-09-24 at 11 56 30 am" src="https://cloud.githubusercontent.com/assets/10667949/10078687/c6aaa94c-62b3-11e5-9923-d686ab11c389.png">

Please advise!

**Comment by yesnault** [comment]
try : 
```
docker exec -it phabricator /bin/bash
cd /opt/phabricator/bin
./storage upgrade
```

**Comment by yesnault** [comment]
A new image is uploaded on hub.docker.com, seems all working.
Feel free to reopen this issue if it's not working for you.
