### ISSUE TITLE
Unable to connect to MySQL!

### ISSUE THREAD

**Issue by tiensonqin** [yesnault/docker-phabricator#42]
Unable to connect to MySQL!

Attempt to connect to admin@database failed with error #2003: Can't connect to MySQL server on 'database' (111).

**Comment by yesnault** [comment]
You've got this error after running theses two containers ?

```
docker run --name databasePhabricator yesnault/docker-phabricator-mysql
docker run -p 8081:80 --link databasePhabricator:database yesnault/docker-phabricator 
```

**Comment by yesnault** [comment]
feel free to reopen this issue if you have this error after starting yesnault/docker-phabricator-mysql and yesnault/docker-phabricator
