### ISSUE TITLE
error when running containers

### ISSUE THREAD

**Issue by arnaudgelas** [yesnault/docker-phabricator#46]
Here is what I get when running containers.

Bad "Host" Header
This request included an invalid "Host" header, with value "localhost:8081". Host headers must contain a dot ("."), like "example.com". This is required for some browsers to be able to set cookies.

This may mean the base URI is configured incorrectly. You must serve Phabricator from a base URI with a dot (like "https://phabricator.mycompany.com"), not a bare domain (like "https://phabricator/"). If you are trying to use a bare domain, change your configuration to use a full domain with a dot in it instead.

This might also mean that your webserver (or some other network device, like a load balancer) is mangling the "Host" header, or you are using a tool or library to issue a request manually and setting the wrong "Host" header.

Requests must include a valid "Host" header.
To continue, resolve this problem and reload the page.
Host: d3ddac3a4e17

**Comment by arnaudgelas** [comment]
What should I do to make it work?
Thanks

**Comment by Fresheyeball** [comment]
This is a phabricator thing. The url needs a `.` use `http://127.0.0.1/` instead of `localhost`
