### ISSUE TITLE
THIS IMAGE IS UNMAINTAINED -- USING AUG 2015 COMMITS

### ISSUE THREAD

**Issue by bddenhartog** [yesnault/docker-phabricator#58]
I would not recommend using this image, which uses extremely old commits:

- **Phabricator** - [`79f2e81f38bed6f2cf0b938ccbd0383a5bc3c9b2`](https://secure.phabricator.com/rP79f2e81f38bed6f2cf0b938ccbd0383a5bc3c9b2) (Aug 8 2015)
- **Arcanist** - [`c304c4e04564cab8b11104e7814376223dc82468`](https://secure.phabricator.com/rARCc304c4e04564cab8b11104e7814376223dc82468) (Aug 7 2015)
- **libphutil** - [`55f554b618b98bdd5970d1ea60db94c7d1dfd61f`](https://secure.phabricator.com/rPHU55f554b618b98bdd5970d1ea60db94c7d1dfd61f) (Aug 5 2015)

Please track containerly/docker-library#73 for progress on a Phabricator image that is kept up to date automatically.

**Comment by jsm** [comment]
This docker repo is not consistently built and tested, but you can build it yourself with different arguments

https://github.com/yesnault/docker-phabricator/blob/master/Dockerfile#L39

**Comment by bddenhartog** [comment]
Yes, that is possible, but users following the [instructions](https://github.com/yesnault/docker-phabricator#run-with-image-from-hubdockercom) aren't likely to think about building the image themselves.

**Comment by yesnault** [comment]
Readme updated.
