### ISSUE TITLE
When I run containers both processes keeps open in terminal.

### ISSUE THREAD

**Issue by swapnilpatil1682** [yesnault/docker-phabricator#59]
Hi, Your image is very helpful. But I am facing one issue. Whenever I run both containers in command line both processes keep open in command line. If I close the terminal both container's  gets stopped. What should I do run these processes in background as others do ? Please help. Your help is much appreciated.

**Comment by jsm** [comment]
If you're running using `docker run`, you can pass in the `-d` flag to run it in the background as a daemon

`docker run -d yesnault/phabricator`
